###############################################################################
# Replica Count
###############################################################################
replicaCount: 1
###############################################################################
# Container Image
###############################################################################
image:
  repository: docker.io/nikhilmhatre0317/retail_platform_ui
  tag: "caa2c96"
  pullPolicy: IfNotPresent
###############################################################################
# Service
###############################################################################
service:
  type: ClusterIP
  port: 80
  targetPort: 8080
###############################################################################
# Ingress
###############################################################################
ingress:
  enabled: true
  className: nginx
  host: ui.local
###############################################################################
# Resources
###############################################################################
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
###############################################################################
# Application Configuration
###############################################################################
config:
  springProfile: prod
  applicationName: ui
  loggingLevel: INFO
  featureXEnabled: "false"
###############################################################################
# Secrets
###############################################################################
secret:
  dbUsername: admin
  dbPassword: password123
  jwtSecret: my-super-secret-key
