###############################################################################
# Secret
#
# Stores sensitive configuration such as passwords, API keys and tokens.
#
# NOTE:
# Kubernetes stores Secrets as Base64 encoded values.
# They are NOT encrypted by default.
###############################################################################

apiVersion: v1
kind: Secret

metadata:

  ###########################################################################
  # Resource Name
  ###########################################################################
  name: {{ include "ui.fullname" . }}-secret

  ###########################################################################
  # Common Labels
  ###########################################################################
  labels: {{ include "ui.labels" . | nindent 4 }}

type: Opaque

###############################################################################
# stringData
#
# Kubernetes automatically converts these values into Base64.
###############################################################################
stringData:

  DB_USERNAME: {{ .Values.secret.dbUsername | quote }}

  DB_PASSWORD: {{ .Values.secret.dbPassword | quote }}

  JWT_SECRET: {{ .Values.secret.jwtSecret | quote }}