###############################################################################
# Service
#
# Exposes the Pods internally within the Kubernetes cluster.
#
# The Service selects Pods using the selector labels defined in
# _helpers.tpl.
###############################################################################

apiVersion: v1
kind: Service

metadata:
  ###########################################################################
  # Resource Name
  ###########################################################################
  name: {{ include "ui.fullname" . }}

  ###########################################################################
  # Common Labels
  ###########################################################################
  labels: {{ include "ui.labels" . | nindent 4 }}

spec:
  ###########################################################################
  # Service Type
  ###########################################################################
  type: {{ .Values.service.type }}

  ###########################################################################
  # Pod Selector
  ###########################################################################
  selector: {{ include "ui.selectorLabels" . | nindent 4 }}

  ###########################################################################
  # Service Ports
  ###########################################################################
  ports:
    - name: http

      port: {{ .Values.service.port }}

      targetPort: http

      protocol: TCP
